# Generated by Django 3.1.5 on 2021-02-23 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyage',
            name='destination',
        ),
        migrations.AddField(
            model_name='destination',
            name='voyage',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='voyage.voyage'),
            preserve_default=False,
        ),
    ]
