# Generated by Django 3.1.5 on 2021-03-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0003_auto_20210223_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='photo',
            field=models.URLField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='photo',
            field=models.URLField(max_length=5000),
        ),
    ]
