# Generated by Django 3.1.5 on 2021-03-06 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0004_auto_20210306_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='voyage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyage.voyage'),
        ),
    ]
